Repository SISPROV6/infra-code-libs, pull requests merged in 2025-07, with the labels that each got.

#59 Ajuste no header
  projects/ngx-sp-infra/package.json
  projects/ngx-sp-infra/src/lib/infra.module.ts
  projects/ngx-sp-infra/src/lib/widgets/auditoria-button/auditoria-button.component.html
  projects/ngx-sp-infra/src/lib/widgets/auditoria-button/auditoria-button.component.scss
  projects/ngx-sp-infra/src/lib/widgets/auditoria-button/auditoria-button.component.ts
  projects/ngx-sp-infra/src/lib/widgets/lib-header/lib-header.component.ts
  projects/ngx-sp-infra/src/lib/widgets/sub-menu-card/sub-menu-card.component.scss
  projects/ngx-sp-infra/src/lib/widgets/sub-menu-card/sub-menu-card.component.ts
  projects/ngx-sp-infra/src/public-api.ts
Labels: enhancement

#62 Fix/alerts
  projects/ngx-sp-infra/package.json
  projects/ngx-sp-infra/src/lib/message/alert/alert.component.html
  projects/ngx-sp-infra/src/lib/message/alert/alert.component.ts
  projects/ngx-sp-infra/src/lib/message/message.service.ts
Labels: enhancement

#63 Test para Next
  projects/ngx-sp-infra/package.json
  projects/ngx-sp-infra/src/lib/models/queue-service/JobRequest.ts
  projects/ngx-sp-infra/src/lib/service/queue.service.ts
  projects/ngx-sp-infra/src/public-api.ts
Labels: enhancement

#71 Ajustes de código do Date-Picker
  projects/ngx-sp-infra/src/lib/infra.module.ts
  projects/ngx-sp-infra/src/lib/modules/lib-widgets.module.ts
  projects/ngx-sp-infra/src/lib/widgets/lib-date-range-picker/lib-date-range-picker.component.html
  projects/ngx-sp-infra/src/lib/widgets/lib-date-range-picker/lib-date-range-picker.component.scss
  projects/ngx-sp-infra/src/lib/widgets/lib-date-range-picker/lib-date-range-picker.component.spec.ts
  projects/ngx-sp-infra/src/lib/widgets/lib-date-range-picker/lib-date-range-picker.component.ts
  projects/ngx-sp-infra/src/public-api.ts
Labels: enhancement

#81 Ordenação corrigida e melhorias no código do componente de ordering
  projects/ngx-sp-infra/src/lib/utils/utils.ts
  projects/ngx-sp-infra/src/lib/widgets/ordering/ordering.component.html
  projects/ngx-sp-infra/src/lib/widgets/ordering/ordering.component.scss
  projects/ngx-sp-infra/src/lib/widgets/ordering/ordering.component.ts
  projects/ngx-sp-infra/src/lib/widgets/table/table.component.ts
Labels: bug, enhancement

#82 Borda do container removida
  projects/ngx-sp-infra/src/assets/styles/global.scss
  projects/ngx-sp-infra/src/lib/widgets/content-container/content-container.component.scss
Labels: enhancement

#89 ngx-sp-infra | v5.1.1 | Commit automático
  projects/ngx-sp-infra/package.json
Labels: enhancement

#91 Ajuste para exibir cobertura de testes pelo terminal
  projects/ngx-sp-infra/karma.conf.js
Labels: bug, automation

#92 Trocado parâmetro 'sonar.login' pelo 'sonar.token'
  .github/workflows/build.yml
  .github/workflows/main.yml
Labels: automation

#98 ngx-sp-infra | v5.2.3 | Commit automático
  projects/ngx-sp-infra/package.json
Labels: sync

#101 Sincronização | test > next
  .github/workflows/build.yml
  .github/workflows/main.yml
  package.json
  sonar-project.properties
Labels: sync, automation

#105 Novos ícones adicionados
  coverage/ngx-sp-infra/lib/widgets/combobox-multiple-choice/combobox-multiple-choice.component.ts.html
  projects/ngx-sp-infra/package.json
  projects/ngx-sp-infra/src/lib/models/icons/icon.model.ts
Labels: enhancement

#107 ngx-sp-infra | v5.2.9 | Commit automático
  coverage/ngx-sp-infra/lib/widgets/combobox-multiple-choice/combobox-multiple-choice.component.ts.html
  projects/ngx-sp-infra/package.json
  projects/ngx-sp-infra/src/lib/models/icons/icon.model.ts
Labels: enhancement

#118 abas
  projects/ngx-sp-infra/package.json
  projects/ngx-sp-infra/src/lib/infra.module.ts
  projects/ngx-sp-infra/src/lib/widgets/empresa-abas/empresa-abas.component.html
  projects/ngx-sp-infra/src/lib/widgets/empresa-abas/empresa-abas.component.scss
  projects/ngx-sp-infra/src/lib/widgets/empresa-abas/empresa-abas.component.ts
  projects/ngx-sp-infra/src/lib/widgets/empresa-abas/models/links-record.ts
  projects/ngx-sp-infra/src/lib/widgets/estabelecimento-abas/estabelecimento-abas.component.html
  projects/ngx-sp-infra/src/lib/widgets/estabelecimento-abas/estabelecimento-abas.component.scss
  projects/ngx-sp-infra/src/lib/widgets/estabelecimento-abas/estabelecimento-abas.component.ts
  projects/ngx-sp-infra/src/lib/widgets/estabelecimento-abas/models/estabelecimentoUriRecord.ts
  projects/ngx-sp-infra/src/lib/widgets/grupo-contabil-abas/grupo-contabil-abas.component.html
  projects/ngx-sp-infra/src/lib/widgets/grupo-contabil-abas/grupo-contabil-abas.component.scss
  projects/ngx-sp-infra/src/lib/widgets/grupo-contabil-abas/grupo-contabil-abas.component.ts
  projects/ngx-sp-infra/src/lib/widgets/grupo-contabil-abas/models/links-record.ts
  projects/ngx-sp-infra/src/lib/widgets/items-abas/items-abas.component.html
  projects/ngx-sp-infra/src/lib/widgets/items-abas/items-abas.component.scss
  projects/ngx-sp-infra/src/lib/widgets/items-abas/items-abas.component.ts
  projects/ngx-sp-infra/src/lib/widgets/items-abas/models/links-record.ts
  projects/ngx-sp-infra/src/lib/widgets/pessoa-abas/models/CrpInPapelRecord.ts
  projects/ngx-sp-infra/src/lib/widgets/pessoa-abas/models/PessoasUriRecord.ts
  projects/ngx-sp-infra/src/lib/widgets/pessoa-abas/models/RetPapeis.ts
  projects/ngx-sp-infra/src/lib/widgets/pessoa-abas/models/RetTipoPessoa.ts
  projects/ngx-sp-infra/src/lib/widgets/pessoa-abas/pessoa-abas.component.html
  projects/ngx-sp-infra/src/lib/widgets/pessoa-abas/pessoa-abas.component.scss
  projects/ngx-sp-infra/src/lib/widgets/pessoa-abas/pessoa-abas.component.ts
  projects/ngx-sp-infra/src/lib/widgets/pessoa-abas/service/pessoa.service.ts
  projects/ngx-sp-infra/src/lib/widgets/usuario-abas/models/links-record.ts
  projects/ngx-sp-infra/src/lib/widgets/usuario-abas/usuario-abas.component.html
  projects/ngx-sp-infra/src/lib/widgets/usuario-abas/usuario-abas.component.scss
  projects/ngx-sp-infra/src/lib/widgets/usuario-abas/usuario-abas.component.ts
  projects/ngx-sp-infra/src/public-api.ts
Labels: components

#120 Fix/sub menu
  projects/ngx-sp-infra/package.json
  projects/ngx-sp-infra/src/lib/widgets/sub-menu-card/sub-menu-card.component.ts
  projects/ngx-sp-infra/src/lib/widgets/sub-menu/nav-tabs/nav-tabs.component.html
  projects/ngx-sp-infra/src/lib/widgets/sub-menu/nav-tabs/nav-tabs.component.ts
  projects/ngx-sp-infra/src/lib/widgets/sub-menu/sub-menu.component.html
Labels: enhancement

#123 ngx-sp-infra | v5.7.5 | Commit automático
  projects/ngx-sp-infra/package.json
  projects/ngx-sp-infra/src/lib/widgets/content-container/content-container.component.html
  projects/ngx-sp-infra/src/lib/widgets/content-container/content-container.component.scss
  projects/ngx-sp-infra/src/lib/widgets/content-container/content-container.component.ts
Labels: enhancement, components

#124 ngx-sp-infra | v5.7.6 | Commit automático
  projects/ngx-sp-infra/package.json
  projects/ngx-sp-infra/src/lib/models/table/header-structure.model.ts
  projects/ngx-sp-infra/src/lib/widgets/lib-simplified-table/lib-simplified-table.component.html
Labels: enhancement

#131 ngx-sp-auth | v2.1.6 | Commit automático
  .github/workflows/main.yml
  deploy/release-info.json
  projects/ngx-sp-auth/package-lock.json
  projects/ngx-sp-auth/package.json
Labels: ci-cd

#132 ngx-sp-infra | v5.7.13 | Commit automático
  .github/workflows/main.yml
  deploy/release-info.json
  projects/ngx-sp-infra/package.json
Labels: ci-cd

#134 Sincronização e atualização do script de deploy
  .github/workflows/build.yml
  .github/workflows/main.yml
  deploy/index.js
  deploy/release-info.json
  package-lock.json
  package.json
  projects/ngx-sp-auth/karma.conf.js
  projects/ngx-sp-auth/package-lock.json
  projects/ngx-sp-auth/package.json
  projects/ngx-sp-infra/package.json
Labels: enhancement, ci-cd
